import re

def normalise_unicode(text):
    text = text.strip()
    text = re.sub(r"אַ", r"אַ", text)
    text = re.sub(r"אָ", r"אָ", text)
    text = re.sub(r"בּ", r"בּ", text)
    text = re.sub(r"בֿ", r"בֿ", text)
    text = re.sub(r"וּ", r"וּ", text)
    text = re.sub(r"יִ", r"יִ", text)
    text = re.sub(r"ײַ", r"ײַ", text)
    text = re.sub(r"כּ", r"כּ", text)
    text = re.sub(r"פּ", r"פּ", text)
    text = re.sub(r"פֿ", r"פֿ", text)
    text = re.sub(r"שׂ", r"שׂ", text)
    text = re.sub(r"תּ", r"תּ", text)
    text = re.sub(r"יי", r"ײ", text)
    text = re.sub(r"וו", r"װ", text)
    text = re.sub(r"וי", r"ױ", text)
    text = re.sub(r"-", r"־", text)
    return text.strip()