declare -a arr=("adorf"
				"ashtiler"
				"ateater"
				"ayzik"
				"baym"
				"baynakht"
				"bontshe"
				"derkhilef"
				"deryid"
				"deryoyred"
				"derziveg"
				"dilandonishe"
				"dimayses"
				"dimentshn"
				"dinodl"
				"doktoyrim"
				"dreyfus"
				"farvos"
				"getsi"
				"kidalto"
				"mark"
				"nakhes"
				"nakhesmono"
				"oybnisht"
				"oysgetreyslt"
				"rebmoyshe"
				"refoel"
				"shloyme"
				"sholem"
				"tayves"
				"yankev"
				"zibngute"
				"zisl")

# now loop through the above array
for book in "${arr[@]}"
do
   echo "$book"
   mkdir books/blacher-retter/segmented_audios/$book
   python3 split.py "books/blacher-retter/json/$book.json" books/blacher-retter/wavs/$book.wav books/blacher-retter/segmented_audios/$book/
done
